enum ATTRIBUTES {
  Allergy = "Allergy",
  Artillerist = "Artillerist",
  CjillingTouch = "Chilling Touch",
  CombatEnginner = "Combat Enginner",
  CombatRider = "Combat Rider",
  DamageReduction = "Damage Reduction",
  DemonicFire = "Demonic Fire",
  Etheral = "Ethereal",
  ExpertClimber = "Expert Climber",
  Flying = "Flying",
  GreatFaith = "Great Faith",
  HardToPutDown = "Hard to Put Down",
  Hypnotic = "Hypnotic",
  InimicalToTechnology = "Inimical to Technology",
  Inspiring = "Inspiring",
  Indefatigable = "Indefatigable",
  Indestructable = "Indestructable",
  Irritant = "Irritant",
  Large = "Large",
  MasterOfCover = "Master of Cover",
  Medic = "Medic",
  Miracles = "Miracles",
  MonsterExpert = "Monster Expert",
  Nimble = "Nimble",
  QuickHealing = "Quick Healing",
  QuickLoad = "Quick Load",
  Range = "Range",
  RockHurler = "Rock Hurler",
  SoulShear = "Soul Shear",
  SupernaturalVeteran = "Supernatural Veteran",
  Skinshift = "Skinshift",
}

export default ATTRIBUTES;
